### ISSUE TITLE
Input vector based FFMatrixGen generator

### ISSUE THREAD

**Issue by lepisma** [unique-horn/ppap#5]

**Comment by Hippogriff** [comment]
Have a look.

**Comment by lepisma** [comment]
[Here](https://github.com/unique-horn/ppap/blob/master/ppap/layers/ppgen.py#L86-L115) is the specification I was thinking of. I lost the notebook which uses this layer, but essentially, a `z` input allowed me to supply a vector of certain length during training for each instance. It could be:

- Random (or noisy around a mean type) vector
- A vector dependent on input / output (a weak form of conditioning; passed on while supplying training/testing data)
- A vector coming from another tensor layer (actual dynamic filter network conditioning).

So, I might (say) do something like
```
input     →     ppconv
   ↘              ↗
    conv → flatten
```

Or something similar.
